language: node_js
node_js:
  - "lts/*"

services: docker

branches:
  only:
    - master

before_install:
  - docker -v
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
install:
  - ./build-web.sh
  - docker-compose build
script:
  - docker push mancuniansam/recipes-server
  - docker push mancuniansam/recipes-web
