language: node_js

services: docker

branches:
  only:
    - master

before_install:
  - docker -v
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
install:
  - docker-compose build
  - docker tag recipe-server mancuniansam/recipes-server
  - docker tag recipe-web mancuniansam/recipes-web
  - build-web.sh
script:
  - docker push mancuniansam/recipes-server
  - docker push mancuniansam/recipes-web
