version: "3"
services:
  recipe-server:
    build:
      context: ./server
    image: recipe-server:latest
    ports:
      - 3000:8084/tcp

  recipe-web:
    build:
      context: ./web
    image: recipe-web:latest
    ports:
      - 80:8085/tcp
