version: "3"
services:
  recipe-server:
    build:
      context: ./server
    image: mancuniansam/recipes-server:latest
    environment:
      - REACT_APP_SERVER_URL=http://localhost:3002
    ports:
      - 3002:8084/tcp
    networks:
      recipes_net:
        ipv4_address: 173.17.238.3

  recipe-web:
    build:
      context: ./web
    image: mancuniansam/recipes-web:latest
    ports:
      - 8085:80/tcp
    networks:
      recipes_net:
        ipv4_address: 173.17.238.2
networks:
  recipes_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.238.0/24
